Feature/17
kikudesuyo/economEye pull request #1
Opened 2024-02-27 00:25 UTC by kikudesuyo

2024-03-29 15:03 UTC, eteRnaL198 requested changes
ざっと確認して気になった所コメントしました

あと､ブランチ名はfeature/17じゃなくてdevで良いような｡ 機能ごとにブランチを分けるのが理想だけど､面倒だよね
1つのブランチで書き続けちゃうと､レビューがしづらくなる

2024-03-29 15:03 UTC, eteRnaL198 commented on src/pages/auth/login/Login.tsx
> +      />
Buttonのfuncに渡す関数を別で定義して､渡すだけにしたい
return()の中身はUIに専念させたくて､ロジックはあんまり書きたくない

```javascript
...
const navigate = useNavigate();
const handleClick = async () => { // returnより上の部分で書いておく｡もしくはhelperファイルで定義する
 if (!isValidEmail(email) {
  ...
}

return (
...
 <Button
    label="ログイン"
    func={handleClick} // ここは渡すだけ
```

2024-03-29 15:03 UTC, eteRnaL198 commented on src/pages/auth/signup/Signup.tsx
> +          }
こちらも同様に､別で定義した関数を渡す形にしたい

2024-03-30 10:28 UTC, kikudesuyo commented on src/imgs/padlock.jpg
098c65a
修正しました

2024-03-30 10:30 UTC, kikudesuyo commented on firestore.rules
> +    match /{document=**} {
firestore.rulesもデプロイするようにします

2024-03-30 10:33 UTC, kikudesuyo commented on src/utils/helper/type.ts
> +export type NumberOrNull = number | null;
1c8cfc5 
修正しました

2024-03-30 10:37 UTC, kikudesuyo commented on src/firebase/firestore/checkRegistration.ts
> +  }
d8a256f 
修正しました

2024-03-30 10:47 UTC, kikudesuyo commented on src/firebase/firestore/checkRegistration.ts
> +  }
ea099cf 
修正しました

2024-03-30 10:52 UTC, kikudesuyo commented on src/firebase/functions/functionsHandler.ts
> +    throw new Error("登録に失敗しました。");
1f1870b 
修正しました

2024-03-30 11:58 UTC, kikudesuyo commented on functions/src/index.ts
e1d5d47
修正しました

2024-03-30 12:04 UTC, kikudesuyo commented on src/pages/auth/signup/Signup.tsx
> +          }
e685a3b 
修正しました

2024-03-30 12:04 UTC, kikudesuyo commented on src/pages/auth/login/Login.tsx
> +      />
4df5afe

2024-03-30 14:57 UTC, eteRnaL198 approved these changes
LGTM!

2024-03-30 14:58 UTC, merged